services:
  pugx.i18n.event.adapter:
    class:     PUGX\I18nBundle\Mapping\Event\Adapter\ORM\DoctrineAdapter
  pugx.i18n.locale:
      class:     PUGX\I18nBundle\Locale\Locale
      arguments: [%locale%]    
  pugx.i18n.locale_listener:
      class:     PUGX\I18nBundle\Listener\LocaleListener
      arguments: ["@pugx.i18n.locale"]
      tags:
          - { name: kernel.event_subscriber }
  pugx.i18n.translatable_listener:
      class:     PUGX\I18nBundle\Listener\TranslatableListener
      arguments: ["@pugx.i18n.event.adapter", "@pugx.i18n.locale"]
      tags:
          - { name: doctrine.event_subscriber }