--- 
php: 
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1

notifications: 
  email: 
  - leonardo.proietti@gmail.com
before_script: 
- curl -s http://getcomposer.org/installer | php
- php composer.phar install --dev
env: 
  matrix: 
    secure: |-
      OcBJDA8S2ZrCForyUPjiR1vcqDS6K/L/fNqDQVeAsJ+GUk4hXAHE7ui8TCX9
      HX3CWAxHLjZKQLStjNyKymPRPPTrKp9tVtgkU1EinsaEBn3L2KKZ2N684pRw
      sux0cqKmThtwULlspaVmAVzR/jKQM/xqW0neogE3q8+OGx3KICA=
language: php
